security:

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
                require_previous_session: false

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/private, roles: ROLE_USER }
